development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://:Styr6z0UYOPkYf79EXDD106DA5wMA007@redis-16670.c89.us-east-1-3.ec2.cloud.redislabs.com:16670" } %>
  channel_prefix: message_us_production
